version: "3.3"
services:
  postgres:
    container_name: db-freight
    image: "postgres:14.1-alpine"
    restart: always
    environment:
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=freight
    ports:
       - '5432:5432'
    volumes: 
      - ./postgress-data:/var/lib/postgresql/data
      - ./scripts_sql/create.sql:/docker-entrypoint-initdb.d/create.sql



#docker run --name basic-postgres --rm -e POSTGRES_USER=john -e POSTGRES_PASSWORD=1234 -e POSTGRES_DB=freight -p 5432:5432 -it postgres:14.1-alpine
